database:
  uri: mongodb://localhost:27017
  name: chiketto

redis:
  dbIndex: 0
  url: redis://:p3048f7933cdd45aed6663e7ffeb3c777e0cb36663dc91545f9bc151fc2332ab8@ec2-44-210-204-108.compute-1.amazonaws.com:7479

authentication:
  cookieDomain: localhost
  jwt:
    accessTokenSecret: yCD0QVMLR2He9uO1i72N7otvAMC4UPgHpBO6bAgTybhal0nCJi7Yjete86kcBrYh
    refreshTokenSecret: hMQwLDflPa2vxAJfITCZiEMtaTwpDYvGwti3YDpx3JKOIIldDwTe2VMUAzg9JHFU

cors:
  allowOrigins: http://localhost:2000, http://localhost:3000, http://localhost:4000

servers:
  server:
    host: localhost
    port: 2000
    publicUrl: http://localhost:2000
  admin:
    host: localhost
    port: 3000
    publicUrl: http://localhost:3000
  main:
    host: localhost
    port: 4000
    publicUrl: http://localhost:4000
