database:
  uri: mongodb://localhost:27017
  name: chiketto

redis:
  dbIndex: 0
  url: redis://localhost:6379

authentication:
  cookieDomain: localhost
  jwt:
    accessTokenSecret: a random string
    refreshTokenSecret: a random string

cors:
  allowOrigins: http://localhost:2000, http://localhost:3000, http://localhost:4000

servers:
  server:
    host: localhost
    port: 2000
    publicUrl: http://localhost:2000
  admin:
    host: localhost
    port: 3000
    publicUrl: http://localhost:3000
  main:
    host: localhost
    port: 4000
    publicUrl: http://localhost:4000
