database:
  uri: CHIKETTO_DATABASE_URI
  name: chiketto

redis:
  dbIndex: 0
  url: CHIKETTO_REDIS_URL

authentication:
  cookieDomain: CHIKETTO_AUTHENTICATION_COOKIEDOMAIN
  jwt:
    accessTokenSecret: CHIKETTO_AUTHENTICATION_JWT_ACCESSTOKENSECRET
    refreshTokenSecret: CHIKETTO_AUTHENTICATION_JWT_REFRESHTOKENSECRET

cors:
  allowOrigins: CHIKETTO_CORS_ALLOWORIGINS

server:
  api:
    host: 0.0.0.0
    port: 80
    publicUrl: CHIKETTO_SERVER_API_PUBLICURL
  admin:
    host: 0.0.0.0
    port: 80
    publicUrl: CHIKETTO_SERVER_ADMIN_PUBLICURL
  main:
    host: 0.0.0.0
    port: 80
    publicUrl: CHIKETTO_SERVER_MAIN_PUBLICURL
